### ISSUE TITLE
Search by Filename (GOES and NEXRAD)

### ISSUE THREAD

**Issue by shankar-dh** [BigDataIA-Spring2023-Team-09/DAMG_7245#14]
The personal S3 bucket link is returned where it should have returned both the Personal S3 bucket link and NOAA S3 public link

- Issue raised by Team7

**Comment by Hmittal15** [comment]
NOAA S3 public link was to be returned only when the user searches by filters, and not when they search by filename. Since, it was not part of the requirement, we only implemented it for 'Seach by filter' functionality.
